name: Build and Push Docker Images

on:
  push:
    branches:
      - master
    paths:
      - 'backend/**'

env:
  DOCKER_USERNAME: varshithchand

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Backend Image
      - name: Build Backend Image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            varshithchand/eduvault-backend:latest
            varshithchand/eduvault-backend:${{ github.sha }}

      # Frontend Image
      - name: Build Frontend Image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            varshithchand/eduvault-frontend:latest
            varshithchand/eduvault-frontend:${{ github.sha }}
